version: '3'
services:
 large-app:
  image: registry-docker.portainercloud.io/library/alpine:latest
  volumes:
      - ../html:/home/html
  tty: true
  stdin_open: true
  environment:
   - hello=hi
   - fire=bending
   - foo=barre
